### ISSUE TITLE
The readme and the code are not on sync

### ISSUE THREAD

**Issue by fraxedas** [nmarus/sparky#1]
The doc for getting messages from the room: https://github.com/nmarus/sparky/blob/master/README.md#sparkymessagesroomgetroomid-max-callbackerror-results
Is not on sync with the code: https://github.com/nmarus/sparky/blob/master/lib/sparky.js#L289

(Thanks for the npm package)

**Comment by nmarus** [comment]
Consider this a hidden feature at the moment. :) The max parameter is optional and the function will execute as documented without specifying a max. It is parsing the the first and last function args into roomid and callback while defaulting max to the global value if not specified at the function call.

**Comment by fraxedas** [comment]
Hi @nmarus 
The function to retrieve messages for a specified room is documented as:
`sparky.messages.room.get`
But the in code is used as:
`sparky.messages.get`
There's no **room** in the function signature.

(again, thanks for the package. It got me up and running with spark in no time)

**Comment by nmarus** [comment]
Ha. I totally missed that in your initial message. Good catch. I'll update docs. 👍
