### ISSUE TITLE
ReDos via long string of semicolons

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [nmarus/sparky#3]
Getting this message at npm install

> npm install node-sparky
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie 
https://nodesecurity.io/advisories/130

**Comment by ObjectIsAdvantag** [comment]
Seems the CVE was published July 22nd

Remediation: Upgrade to at least version 2.3.0

**Comment by nmarus** [comment]
Thanks for letting me know. It must be a dependency of a dependency. I'll see which one it is and if they have patched it.

**Comment by nmarus** [comment]
Looks like request@2.72 was depending on "tough-cookie". They fixed this in request@2.74. I updated the package.json file to reflect the updated dependency. node-sparky@3.1.16 has the updated dependencies now. Thanks again!
